version: 2.1

commands:
    
jobs:

# ##########################Building Section #################################################################################################

  build-app:
    build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
                    at: ~/
      - run:
                name: Install dependencies
                command: |
                        pip install -r requirements.txt
                        pip list
                        ls

  lint-app:
    build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
                    at: ~/
      - run:
                name: Install dependencies
                command: |
                        pip install -r requirements.txt
                        pip list
      - run:
                name: lint app
                command: |
                        pylint --disable=R,C,W1203 app.py                                                

  scan-app:
    build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
                    at: ~/
      - run:
                name: Install dependencies
                command: |
                        pip install --upgrade pip
                        pip install -r requirements.txt
                        safety check

  docker-app:
    build:
    docker:
      - image: amazon/aws-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run: yum -y install tar gzip
      - attach_workspace:
                    at: ~/
      - run:
                name: Install dependencies
                command: |
                        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r3i6g3s9
                        docker build -t number5 .
                        docker tag number5:latest public.ecr.aws/r3i6g3s9/number5:latest
                        docker push public.ecr.aws/r3i6g3s9/number5:latest
                     


workflows:
  default:
    jobs:
      - build-app
      - lint-app:
          requires: [build-app]
      - scan-app:
          requires: [lint-app]
      - docker-app:
          requires: [scan-app]          
