version: 2.1

commands:
    
jobs:

# ##########################Building Section #################################################################################################

  build-app:
    build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
                    at: ~/
      - run:
                name: Install dependencies
                command: |
                        apt-get -y update
                        pip install -r requirements.txt
                        pip list
                        ls
                        python app.py
workflows:
  default:
    jobs:
      - build-app
