version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: https://us-west-2.console.aws.amazon.com/ecr/repositories?region=us-west-2
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: number5
          profile-name: myProfileName
          region: AWS_REGION_ENV_VAR_NAME
          repo: myECRRepository
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'